### ISSUE TITLE
Tool does not properly handle non-Ascii characters

### ISSUE THREAD

**Issue by The3IC** [sm18lr88/Audacity_Subtitle_Generator_Plugin#1]
First of all, kudos for a nice module that nicely supports the Openvivo tool.

I have a problem processing languages with "accented" characters, eg in my case tested on Finnish and the Finnish letters such as "ä" and "ö" which get replaced by "_". So the Finnish word "tämä" shows up as "t_m_". Also all 8-bit characters show up as the same "_", so it is not possible to do a simple search and replace.

I assume that Audacity on Windows uses Unicode so these characters are encoded with 2 bytes so just "copying" from Audacity to UTF-8 does not work.

Seeing that the .srt file has been UTF-8 encoded, the tool should at least support the full UTF-8 character set meaning at least 2-byte Unicode characters.

**Comment by sm18lr88** [comment]
Sorry to take so long to get back to you, I'm in the middle of travelling. Will definitly check this out though.

**Comment by sm18lr88** [comment]
Hey @The3IC, I spent a few hours trying to figure it out.

Turns out the Nyquist plugin language itself can't accomplish this.

I tried creating a plugin that integrates into Audacity itself, but it's way more involved than I have time for.

So I created some files that you can use to convert an exported label text file into .srt.

You can just double-click on this [file](https://github.com/sm18lr88/Audacity_Subtitle_Generator_Plugin/blob/main/manual/label-to-srt.exe) and choose the text file, and it will convert it right away.

Sorry for this limitation.
